WAR3/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using AutoMapper.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OfficeOpenXml.FormulaParsing.ExpressionGraph.FunctionCompilers;
using WAR3.Dtos;
using WAR3_DAL.Dtos;
using WAR3_DAL.Entities;
using WAR3_DAL.Implementation.IRepositories;
using WAR3_DAL.ViewModel;

namespace WAR3.Controllers
{
    public class LoginController : Controller
    {
        
        private IUserRepositories _productService;
        private readonly IHttpClientFactory _httpClientFactory;
       // private readonly IConfiguration _configuration;

        public LoginController( IUserRepositories productService, IHttpClientFactory httpClientFactory/*, IConfiguration configuration*/)
        {
            
            _productService = productService;
            _httpClientFactory = httpClientFactory;
            //_configuration = configuration; ;
        }
        public IActionResult Login()
        {
            if (Request.Cookies["REMENBER"] == "true")
            {
                ViewData["USER_NAME"] = Request.Cookies["USER_NAME"];
                ViewData["PASSWORD"] = Request.Cookies["PASSWORD"];

            }
            if (Request.Cookies["LOAD"] != null)
            {
                Response.Cookies.Delete("LOAD");
            }
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Authen(string UserName,string Password)
        {
            if (Request.Cookies["USER_NAME"] != null)
            {
                Response.Cookies.Delete("USER_NAME");
            }
            if (Request.Cookies["PASSWORD"] != null)
            {
                Response.Cookies.Delete("PASSWORD");
            }
            if (Request.Cookies["NAME"] != null)
            {
                Response.Cookies.Delete("NAME");
            }
            if (Request.Cookies["LOAD"] != null)
            {
                Response.Cookies.Delete("LOAD");
            }
            ////var result1 = await _signInManager.PasswordSignInAsync(UserName, Password,false ,  lockoutOnFailure: false);
            //var model=_productService.GetUserByName(UserName, Password, out bool result, out string message);
            //if(result==true && message== "SUCCESS")
            //{
            //    Response.Cookies.Append("USER_NAME", model[0].USER_NAME);
            //    Response.Cookies.Append("PASSWORD", model[0].PASSWORD);
            //    Response.Cookies.Append("NAME", model[0].NAME);
            //    //ISession.SetString("USER_NAME", model[0].USER_NAME);
            //    //_session.SetString("PASSWORD", model[0].PASSWORD);
            //    //_session.SetString("NAME", model[0].NAME);
            //}
            //try
            //{
            //    var client = _httpClientFactory.CreateClient();
            //    client.BaseAddress = new Uri("https://localhost:44336");
            //    var response = await client.GetAsync($"/api/User/{UserName}/{Password}");
            //    var body = await response.Content.ReadAsStringAsync();
            //    if (response.IsSuccessStatusCode)
            //    {
            //        UserViewModel myDeserializedObjList = (UserViewModel)JsonConvert.DeserializeObject(body,
            //            typeof(UserViewModel));
            //        Response.Cookies.Append("USER_NAME", myDeserializedObjList.USER_NAME);
            //        Response.Cookies.Append("PASSWORD", myDeserializedObjList.PASSWORD);
            //        Response.Cookies.Append("NAME", myDeserializedObjList.NAME);
            //        //if(myDeserializedObjList.)
            //        return new ObjectResult(new GenericResult(true, myDeserializedObjList));

            //    }
            //    return new ObjectResult(new GenericResult(false, response.IsSuccessStatusCode));
            //}
            //catch(Exception ex)
            //{
            //    return new ObjectResult(new GenericResult(false, ex.Message));
            //}
            var data = await GetAsync<PagedResultAPI<UserViewModel>>(
               $"api/User/Login?userName={UserName}" +
               $"&passWord={Password}");
            if(data.Success==true && data.Message!= "NoData") 
                {
                Response.Cookies.Append("USER_NAME", data.Items[0].USER_NAME);
                Response.Cookies.Append("PASSWORD", data.Items[0].PASSWORD);
                Response.Cookies.Append("NAME", data.Items[0].NAME);
                Response.Cookies.Append("LOAD", "1");
            }
            return new OkObjectResult(new GenericResult(data.Success, data.Message, data));

            //var result = _productService.Authenticate( UserName, Password);


        }
        protected async Task<TResponse> GetAsync<TResponse>(string url)
        {


            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("http://192.168.1.168/API/WMS_API/");
            var response = await client.GetAsync(url);
            var body = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode)
            {
                TResponse myDeserializedObjList = (TResponse)JsonConvert.DeserializeObject(body,
                    typeof(TResponse));

                return myDeserializedObjList;
            }
            return JsonConvert.DeserializeObject<TResponse>(body);
        }
        void POST(string url, string jsonContent)
        {
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "POST";

            System.Text.UTF8Encoding encoding = new System.Text.UTF8Encoding();
            Byte[] byteArray = encoding.GetBytes(jsonContent);

            request.ContentLength = byteArray.Length;
            request.ContentType =   "application/json";

            using (Stream dataStream = request.GetRequestStream())
            {
                dataStream.Write(byteArray, 0, byteArray.Length);
            }
            long length = 0;
            try
            {
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                {
                    // got response
                    length = response.ContentLength;
                }
            }
            catch (WebException ex)
            {
                WebResponse errorResponse = ex.Response;
                using (Stream responseStream = errorResponse.GetResponseStream())
                {
                    StreamReader reader = new StreamReader(responseStream, Encoding.GetEncoding("utf-8"));
                    String errorText = reader.ReadToEnd();
                    // log errorText
                }
                throw;
            }
        }




    }
}

WAR3/Controllers/StockingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using WAR3.Dtos;
using WAR3_DAL.Implementation.IRepositories;
using WAR3_DAL.ViewModel;

namespace WAR3.Controllers
{
    public class StockingController : Controller
    {
        private IStockingRepositories _stockingRepositories;
        private readonly IHostingEnvironment _hostingEnvironment;

        public StockingController(IStockingRepositories stockingRepositories, IHostingEnvironment hostingEnvironment)
        {
            _stockingRepositories = stockingRepositories;
            _hostingEnvironment = hostingEnvironment; ;
        }
        public IActionResult Index()
        {
            ViewData["NAME"] = Request.Cookies["NAME"];
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllStocking( string fromDate, string toDate, string keyword, int page, int pageSize)
        {
            var model = await _stockingRepositories.GetAllStocking( fromDate, toDate,keyword, page, pageSize);
            return new OkObjectResult(new GenericResult(model.Success, model.Message, model)); //new OkObjectResult(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> GetStockingById(string id)
        {
            var model = await _stockingRepositories.GetStockingById(id);
            return new OkObjectResult(new GenericResult(model.Success, model.Message, model)); //new OkObjectResult(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStocking( int id, string location)
        {
            var UserName = Request.Cookies["USER_NAME"];
            var data = await _stockingRepositories.UpdateStocking(UserName, id, location);
            return new OkObjectResult(new GenericResult(data.Success, data.Message));
        }
       

       
    }
}

WAR3/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using WAR3.Dtos;
using WAR3_DAL.Entities;
using WAR3_DAL.Implementation.IRepositories;
using WAR3_DAL.ViewModel;

namespace WAR3.Controllers
{
    public class UserController : Controller
    {
        private IUserRepositories _productService;
        private readonly IHttpClientFactory _httpClientFactory;

        public UserController(IUserRepositories productService, IHttpClientFactory httpClientFactory)
        {

            _productService = productService;
            _httpClientFactory = httpClientFactory;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Account()
        {
            ViewData["NAME"] = Request.Cookies["NAME"];
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(User request)
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetUserByUserName()
        {
            var UserName =  Request.Cookies["USER_NAME"];
            var Password= Request.Cookies["PASSWORD"];

            //var model = _productService.GetUserByName(UserName, Password, out bool result, out string message);

            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("http://192.168.1.168/API/WMS_API/");
            var response = await client.GetAsync($"api/User/{UserName}/{Password}");
            var body = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode)
            {
                UserViewModel myDeserializedObjList = (UserViewModel)JsonConvert.DeserializeObject(body,
                    typeof(UserViewModel));
                Response.Cookies.Append("USER_NAME", myDeserializedObjList.USER_NAME);
                Response.Cookies.Append("PASSWORD", myDeserializedObjList.PASSWORD);
                Response.Cookies.Append("NAME", myDeserializedObjList.NAME);
                //if(myDeserializedObjList.)
                return new ObjectResult(new GenericResult(true, myDeserializedObjList));

            }
            return new ObjectResult(new GenericResult(false, response.IsSuccessStatusCode));

            //return new OkObjectResult(new GenericResult(result, message, model)); //new OkObjectResult(model);
        }

        [HttpPost]
        public async Task<IActionResult> SaveUpdateUser(GetUserViewModel request, string Name,string Company, string Address, string Email, string Phone)
        {
            var UserName = Request.Cookies["USER_NAME"];
            var Password = Request.Cookies["PASSWORD"];
            //_productService.SaveUpdateUser(UserName, Password, Name, Company, Address, Email, Phone, out bool result, out string message);
            //if (result == true && message == "SUCCESS")
            //{

            //    Response.Cookies.Append("NAME", Name);
            //}
            //return new OkObjectResult(new GenericResult(result, message)); //new OkObjectResult(model);
            //List<GetUserViewModel> data = new List<GetUserViewModel>();
            //data.add
            //var url = "https://localhost:44336/api/User/UpdateUser";
            //WebRequest request = WebRequest.Create(url);
            //request.Credentials = CredentialCache.DefaultCredentials;
            //request.Method = "POST";
            //byte[] byteArray = Encoding.UTF8.GetBytes(json);

            //ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;


            //// request.ContentType = "application/json"
            //request.ContentType = "application/json";
            //request.ContentLength = byteArray.Length;
            //Stream dataStream1 = request.GetRequestStream();
            //dataStream1.Write(byteArray, 0, byteArray.Length);

            //WebResponse response = request.GetResponse();
            //Stream dataStream = response.GetResponseStream();
            //StreamReader reader = new StreamReader(dataStream);



            //// Dim soapEnvelopeXml As XmlDocument = New XmlDocument

            //// soapEnvelopeXml.LoadXml(kq)

            //// kq = reader.ReadA
            //reader.Close();
            //response.Close();
            List<GetUserViewModel> data = new List<GetUserViewModel> () ;

            data.Add(
       new GetUserViewModel()
       {
           USERNAME = UserName,
           NAME = Name,
           NAMECOMPANY = Company,
           ADDRESS = Address,
           EMAIL = Email,
           PHONE = Phone,
           CREATEUSER = UserName
       }) ;
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("http://192.168.1.168/API/WMS_API/");


            var json = JsonConvert.SerializeObject(data[0]);
            
            var httpContent = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PostAsync($"api/User/UpdateUser", httpContent);
            var result = await response.Content.ReadAsStringAsync();


            //var client = _httpClientFactory.CreateClient();
            //client.BaseAddress = new Uri("https://localhost:44336");

            //var requestContent = new MultipartFormDataContent();

            //requestContent.Add(new StringContent(UserName), "username");
            //requestContent.Add(new StringContent(Name), "name");
            //requestContent.Add(new StringContent(Company), "namecompany");
            //requestContent.Add(new StringContent(Address), "address");
            //requestContent.Add(new StringContent(Email), "email");

            //requestContent.Add(new StringContent(Phone), "phone");

            //var response = await client.PostAsync($"/api/User/UpdateUser", requestContent);
            if (response.IsSuccessStatusCode == true)
            {
                Response.Cookies.Append("NAME", Name);
            }
            return new OkObjectResult(new GenericResult( response.IsSuccessStatusCode,response.ReasonPhrase));
            //return response.IsSuccessStatusCode;
        }

        [HttpPost]
        public async Task<IActionResult> SaveUpdatePass(string PassNew)
        {
            var UserName = Request.Cookies["USER_NAME"];
            List<GetUserViewModel> data = new List<GetUserViewModel>();

            data.Add(
       new GetUserViewModel()
       {
           USERNAME = UserName,
           PASSWORD= PassNew,
           CREATEUSER = UserName
       });
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("http://192.168.1.168/API/WMS_API/");


            var json = JsonConvert.SerializeObject(data[0]);

            var httpContent = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PostAsync($"api/User/UpdatePassWord", httpContent);
            var result = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode == true)
            {
               Response.Cookies.Append("PASSWORD", PassNew);
            }
            return new OkObjectResult(new GenericResult(response.IsSuccessStatusCode, response.ReasonPhrase));
            //_productService.SaveUpdatePass(UserName, PassNew, out bool result, out string message);
            //if (result == true && message == "SUCCESS")
            //{

            //    Response.Cookies.Append("PASSWORD", PassNew);
            //}
            //return new OkObjectResult(new GenericResult(result, message)); //new OkObjectResult(model);
        }
    }
}

WAR3/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"]</title>

    <link href="/css/styles.css" rel="stylesheet" />
    <!-- Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <!-- NProgress -->
    <link href="~/lib/nprogress/nprogress.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" />
    <link href="~/admin-side/css/custom.css" rel="stylesheet" />


    <!-- bootstrap-daterangepicker -->
    @*<link href="~/lib/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />*@
    @*<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />*@
    <link href="~/lib/notify/styles/metro/notify-metro.css" rel="stylesheet" />
    @*<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />*@

    @*<script src="~/lib/font-awesome/js/all.min.js"></script>*@
    @*<script src="~/lib/bootstrap-daterangepicker/daterangepicker.js"></script>*@
    <script src="~/app/Shared/common.js"></script>
    <script src="~/app/Shared/dropdown.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/mustache.js/mustache.js"></script>
    <script src="~/lib/bootstrap-sweetalert/sweetalert.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/moment.js/moment.js"></script>

    @*<script src="~/lib/notify.js/notify.js"></script>*@
    <script src="~/lib/bootbox.js/bootbox.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>*@
    
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <div style="margin-left:-55px;">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="/admin-side/images/logo1.png" alt="..." class="img-circle profile_img" style="margin-top:-3px;width:60px;height:50px;background: #343a40;"> QL Camera</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
                <i class="fas fa-bars"></i>
            </button><!-- Navbar Search-->
        </div>

        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">

            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0" style="margin-right:60px;">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i>@ViewData["NAME"]</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="User" asp-action="Account">Thông tin tài khoản</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Login" asp-action="Login">Đăng xuất</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" asp-controller="Device" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Thiết bị
                            </a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Chấm công
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Statistical" asp-action="Index">Thống kê</a>
                                <a class="nav-link" asp-controller="Statistical" asp-action="InOut">Chi tiết vào ra</a>
                                @*<a class="nav-link" asp-controller="Location" asp-action="Index">Vị trí</a>
                                <a class="nav-link" asp-controller="Contact" asp-action="Index">Liên hệ</a>
                                <a class="nav-link" asp-controller="Pallet" asp-action="Index">Mã Pallet</a>*@
                            </nav>
                        </div>
                        <!--<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Nhập hàng
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link" asp-controller="ImportGoods" asp-action="Index"> Danh sách nhập hàng</a>
                                <a class="nav-link" asp-controller="Stocking" asp-action="Index"> Cất hàng</a>-->
                                @*<a class="nav-link collapsed"asp-controller="ImportGoods" asp-action="Index" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
            Danh sách nhập hàng
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
            Error
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
        </div>*@
                            <!--</nav>
                        </div>-->
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
               
            </nav>
        </div>
        @*<div class="right_col" role="main">
                <div class="">
                    @RenderBody()
                </div>
            </div>*@
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>

        </div>
    </div>
    @*<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>*@
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    @*<script src="/js/scripts.js"></script>*@
    <script src="~/lib/notify/notify.js"></script>
    <script src="~/lib/notify/styles/metro/notify-metro.js"></script>
    <script src="~/lib/twbs-pagination/jquery.twbsPagination.js"></script>
    @*<script src="/assets/demo/chart-area-demo.js"></script>*@

   


    @*<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>

        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>*@
    @*<script src="/assets/demo/datatables-demo.js"></script>*@
</body>
</html>